name = "Raven"
uuid = "9535e987-5000-4019-b381-26e70fd3074d"
authors = ["Jarvist Moore Frost <jarvist@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
IterativeSolvers = "0.9"
julia = "1.6"