name = "Raven"
uuid = "9535e987-5000-4019-b381-26e70fd3074d"
version = "0.1.0"
authors = ["Jarvist Moore Frost <jarvist@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
FFTW = "1.10.0"
IterativeSolvers = "0.9"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.1"
Printf = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.6"
