name = "Raven"
uuid = "9535e987-5000-4019-b381-26e70fd3074d"
authors = ["Jarvist Moore Frost <jarvist@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
IterativeSolvers = "0.9"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
Random = "1.11.0"
Revise = "3.11.0"
julia = "1.6"
