name = "Raven"
uuid = "9535e987-5000-4019-b381-26e70fd3074d"
authors = ["Jarvist Moore Frost <jarvist@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
